### ISSUE TITLE
Switching language breaks site

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/monal-im.org#23]
If I open the about page and switch to german in the header of the post, I get 404 errors when clicking on virtually anything in the menu (e.g. Install, Support etc.).

**Comment by wiseweb-works** [comment]
I found the cause and solution of the problem. The issue is caused by the menu links in `de: > menu: > main:` in the config.yml file. For pages that don't have a translated version (DE), it will be sufficient to change them. To give a brief example:

```
Old:
- identifier: Support
                   name: "Support"
                   url: /support/

Correct:
- identifier: Support
                   name: "Support"
                   url: "../support/"
```

@tmolitor-stud-tu , do you want me to fix this issue with a commit?
